<html>
<head>
    <title>EsiGate is watching you...</title>
</head>
<body>
<esi:fragment name="body">
    This string is generated by the Webapp included with EsiGate.
</esi:fragment>
</body>
</html>
